- name: variables from play level
  hosts: localhost
  tasks:
  - name: check variables
    vars: 
      course: "Devops with aws"
      trainer: "sivakumar sir"
      duration: "110 weeks"
    ansible.builtin.debug:
      msg: "hi i am learning {{course}},my trainer is {{trainer}}.course duration is {{duration}}."   