- name: variables from play level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables from another file
    ansible.builtin.debug:
      msg: "hi i am learning {{course}},my trainer is {{trainer}}.course duration is {{duration}}."