- name: condition
  hosts: localhost
  become: yes
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.comment: id roboshop
    register: user
    ignore-errors: true
  - name: print variable value
    ansible.builtin.debug:
      msg: "status is:{{user.rc}}"