- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install programs
    ansible.builtin.package:
      name: {{item}}
      state: present
    loop:
    - git
    - mysql
    - postfix  