- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install and uninstall programs
    ansible.builtin.package:
      name: "{{item}}"
      state: "{{item}}"
    loop:
    - {name: "postfix", state: "present"}
    - {name: 'nginx', state: 'present'} 
    - {name: 'git', state: 'absent'}
    - {name: 'mysql', state: 'absent'}
     